# Generated by Django 6.0.1 on 2026-01-24 07:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entities_id', models.IntegerField(default=0)),
                ('is_recursive', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('ldap_field', models.CharField(blank=True, max_length=255, null=True)),
                ('ldap_value', models.TextField(blank=True, null=True)),
                ('ldap_group_dn', models.TextField(blank=True, null=True)),
                ('date_mod', models.DateTimeField(blank=True, null=True)),
                ('groups_id', models.IntegerField(default=0)),
                ('completename', models.TextField(blank=True, null=True)),
                ('level', models.IntegerField(default=0)),
                ('ancestors_cache', models.TextField(blank=True, null=True)),
                ('sons_cache', models.TextField(blank=True, null=True)),
                ('is_requester', models.BooleanField(default=True)),
                ('is_watcher', models.BooleanField(default=True)),
                ('is_assign', models.BooleanField(default=True)),
                ('is_task', models.BooleanField(default=True)),
                ('is_notify', models.BooleanField(default=True)),
                ('is_itemgroup', models.BooleanField(default=True)),
                ('is_usergroup', models.BooleanField(default=True)),
                ('is_manager', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'db_table': 'users_groups',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserLoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_login_history',
            },
        ),
    ]
