# Generated by Django 6.0.1 on 2026-01-27 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_platform_status'),
        ('users', '0003_delete_usersgroup_user_force_password_change_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='userrolemapping',
            name='roleId',
        ),
        migrations.RemoveField(
            model_name='userrolemapping',
            name='userId',
        ),
        migrations.AddField(
            model_name='userrolemapping',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master.role'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userrolemapping',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserLoginHistory',
        ),
    ]
