# Generated by Django 6.0.1 on 2026-01-27 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_platform_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='entity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master.entity'),
            preserve_default=False,
        ),
    ]
