# Generated by Django 6.0.1 on 2026-01-23 05:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_platform_status'),
        ('task', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasklist',
            options={'ordering': ['-date', 'task__name']},
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='modified_by',
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='bitrix_id',
            field=models.CharField(blank=True, db_index=True, help_text='External Bitrix ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Hours spent (e.g. 4.50)', max_digits=6),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_entries', to='master.platform'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_entries', to='master.status'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='subtask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtask_entries', to='master.subtask'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_entries', to='master.task'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='tasklist',
            index=models.Index(fields=['user', 'date'], name='task_list_user_id_54c9b5_idx'),
        ),
        migrations.AddIndex(
            model_name='tasklist',
            index=models.Index(fields=['platform', 'status'], name='task_list_platfor_ec8351_idx'),
        ),
        migrations.AddIndex(
            model_name='tasklist',
            index=models.Index(fields=['bitrix_id'], name='task_list_bitrix__5042cf_idx'),
        ),
        migrations.AddIndex(
            model_name='tasklist',
            index=models.Index(fields=['user', 'status'], name='task_list_user_id_bc227a_idx'),
        ),
    ]
