# Generated by Django 6.0.1 on 2026-01-27 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_alter_role_entity'),
        ('task', '0002_alter_tasklist_options_remove_tasklist_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.platform'),
        ),
    ]
