"""
Django settings for time_Sheet project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8w6v%(v!f(e$hu^3@omg*veqqp(0i&36pd84cdfdozd58@vbl4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]']  # ← add these for dev; expand in prod
ALLOWED_HOSTS = ["*"]  # ← add these for dev; expand in prod


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',                     # DRF
    'rest_framework_simplejwt',           # ← add this for JWT
    'corsheaders',
    'master.apps.MasterConfig',
    'users.apps.UsersConfig',
    'task.apps.TaskConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [ 
    "http://localhost:5173", 
]

CORS_ALLOW_ALL_ORIGINS = True
APPEND_SLASH = False
ROOT_URLCONF = 'time_Sheet.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'time_Sheet.wsgi.application'


# ────────────────────────────────────────────────
# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# ────────────────────────────────────────────────

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'TimeSheet',
        'USER': 'postgres',
        'PASSWORD': 'Stemz@123',
        'HOST': 'localhost',          # ← add this (or '127.0.0.1')
        'PORT': '5432',               # ← add default PostgreSQL port
    }
}


# ────────────────────────────────────────────────
# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
# ────────────────────────────────────────────────

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ────────────────────────────────────────────────
# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/
# ────────────────────────────────────────────────

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'            # ← change to your timezone (Chennai)
USE_I18N = True
USE_TZ = True


# ────────────────────────────────────────────────
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
# ────────────────────────────────────────────────

STATIC_URL = 'static/'


# ────────────────────────────────────────────────
# Custom User Model (important!)
# ────────────────────────────────────────────────

AUTH_USER_MODEL = 'users.User'        # ← tells Django to use your custom User model


# ────────────────────────────────────────────────
# Django REST Framework Settings
# ────────────────────────────────────────────────

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        # 'rest_framework.authentication.SessionAuthentication',  # optional - keep if using browsable API
        # 'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',          # most secure default
        # 'rest_framework.permissions.AllowAny',               # use only for public endpoints
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',       # optional - nice for dev
    ],
    # Optional: pagination, throttling, etc.
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}


# ────────────────────────────────────────────────
# Simple JWT Settings
# https://django-rest-framework-simplejwt.readthedocs.io/en/latest/settings.html
# ────────────────────────────────────────────────

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),         # short-lived access token
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),            # longer refresh token
    'ROTATE_REFRESH_TOKENS': True,                          # issue new refresh on refresh
    'BLACKLIST_AFTER_ROTATION': True,                       # blacklist old refresh tokens

    'AUTH_HEADER_TYPES': ('Bearer',),                       # Authorization: Bearer <token>
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',

    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    # Signing key - in production use a separate strong key (not SECRET_KEY!)
    'SIGNING_KEY': SECRET_KEY,                              # ok for dev; change in prod

    'ALGORITHM': 'HS256',
}


# ────────────────────────────────────────────────
# Optional: Logging (very useful in production)
# ────────────────────────────────────────────────

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}